// @generated by protobuf-ts 1.0.13 with parameters enable_angular_annotations,long_type_string
// @generated from protobuf file "WebserverMessaging.proto" (syntax proto3)
// tslint:disable
import { BinaryWriteOptions } from "@protobuf-ts/runtime";
import { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import { BinaryReadOptions } from "@protobuf-ts/runtime";
import { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message SocketLogMessage
 */
export interface SocketLogMessage {
    /**
     * @generated from protobuf field: string logMsg = 1;
     */
    logMsg: string;
}
/**
 * Type for protobuf message SocketLogMessage
 */
class SocketLogMessage$Type extends MessageType<SocketLogMessage> {
    constructor() {
        super("SocketLogMessage", [
            { no: 1, name: "logMsg", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SocketLogMessage>): SocketLogMessage {
        const message = { logMsg: "" };
        if (value !== undefined)
            reflectionMergePartial<SocketLogMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SocketLogMessage): SocketLogMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string logMsg */ 1:
                    message.logMsg = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SocketLogMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string logMsg = 1; */
        if (message.logMsg !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.logMsg);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
export const SocketLogMessage = new SocketLogMessage$Type();
